### ISSUE TITLE
多个问题。

### ISSUE THREAD

**Issue by RealHeart** [baibao132/SquareMinecraftLauncherCore#1]
1.如何指定.minecraft根目录
2.是否可以启动1.7.10 Forge
3.如何取合适内存，Java路径等

**Comment by baibao132** [comment]
1.通过取工作目录来找到.minecraft根目录
2.可以，但是因为bmclapiForge下载地址不断的改变，Forge下载会有点问题
3.取合适内存可以通过判断位数、运行内存的大小这些因素来确定
Java路径，可以通过注册表获得，如果注册表不存在，可以通过取系统磁盘名，然后再对x86和x64的Program Files目录中寻找Java目录再定位到Javaw.exe

**Comment by baibao132** [comment]
目前不支持指定.minecraft目录,只会自动指定启动器目录下的.minecraft目录
可以启动
取合适内存和java内存可以看Wiki，Wiki上有注释
