### ISSUE TITLE
建议优化一下文件目录

### ISSUE THREAD

**Issue by wherewhere** [baibao132/SquareMinecraftLauncherCore#10]
感觉乱七八糟的，很多东西都堆在一个文件里，找起来有些麻烦，如果可以整理一下就好了<img alt="幽灵" src="https://raw.githubusercontent.com/Coolapk-UWP/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" />

**Comment by baibao132** [comment]
因为代码量较多所以会感觉到乱，可以根据wiki找到相应的功能找到相关代码
