### ISSUE TITLE
如何启动forge、fabric、liteloader等版本？

### ISSUE THREAD

**Issue by MRHedan** [baibao132/SquareMinecraftLauncherCore#11]

**Comment by baibao132** [comment]
可以查看wiki找到相关调用函数，而且库中也会有说明

**Comment by baibao132** [comment]
demo代码:https://github.com/baibao132/SquareMinecraftLauncher/blob/master/SquareMinecraftLauncher/wpf/sz.xaml.cs#L338-L620 ，可以参考下
