### ISSUE TITLE
如何进行微软登陆，文档里的一行代码启动可以启动全扩展版本吗，启动游戏后F3左上角的启动器名称可以更改吗

### ISSUE THREAD

**Issue by YUXUAN888** [baibao132/SquareMinecraftLauncherCore#12]
如题，3个问题，谢谢！

**Comment by baibao132** [comment]
微软登陆目前存在问题 ，下一个版本会修复。文档里的一行代码可以启动所有版本，但目前所说的缺少libraries问题之前其他开发者都没出现这种问题，现在突然出现，对这样的问题启动代码我们会删除掉这块代码的。游戏标题可以修改，可以在文档里查看该函数，但使用该函数时必须先检测到游戏界面显示后再调用该函数才会有用

**Comment by baibao132** [comment]
微软登陆，下一个版本发布后会在wiki补全

**Comment by YUXUAN888** [comment]
请问下个版本的发布时间大概是什么时候呢
