### ISSUE TITLE
相关问题已经修复，具体内容可以点开查看

### ISSUE THREAD

**Issue by baibao132** [baibao132/SquareMinecraftLauncherCore#13]
微软登录wiki：https://github.com/baibao132/SquareMinecraftLauncherCore/wiki/SquareMinecraftLauncherCore%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3#%E5%BE%AE%E8%BD%AF%E7%99%BB%E5%BD%95
修复启动游戏一直提示缺少libraries问题
可以获取jre和jdk多个版本，java函数不变，感谢 @wherewhere提供该函数代码
最新版本可以通过nuget更新

**Comment by YUXUAN888** [comment]
请问Java获取能否获取一个列表，列表是所有获取到的java

**Comment by baibao132** [comment]
会获取所有Java列表 包括jre和jdk

**Comment by YUXUAN888** [comment]
新的文档能否更新获取mc下载版本列表具体的用法，就这么几行我老是报错（

**Comment by baibao132** [comment]
> 新的文档能否更新获取mc下载版本列表具体的用法，就这么几行我老是报错（
可以参考下：
https://github.com/baibao132/SquareMinecraftLauncher/blob/master/SquareMinecraftLauncher/wpf/sz.xaml.cs#L258-L268

https://github.com/baibao132/SquareMinecraftLauncher/blob/master/SquareMinecraftLauncher/userControl/Menu.xaml.cs#L69-L79
