### ISSUE TITLE
Forge安装问题

### ISSUE THREAD

**Issue by ClemensMine** [baibao132/SquareMinecraftLauncherCore#2]
当前.minecraft目录下存在1.14.4的游戏版本且已启动过
但是在安装forge时提示“未找到该版本”。
forge版本forge-1.14.4-28.2.0
安装代码如下
`await t.ForgeInstallation(Environment.CurrentDirectory + @"\forge.jar", "1.14.4", t.GetJavaPath());`
当前目录下存在forge.jar文件
异常文本如下
`SquareMinecraftLauncher.SquareMinecraftLauncherException: 未找到该版本
   在 SquareMinecraftLauncher.Minecraft.Tools.UninstallTheExpansionPack(ExpansionPack ExpansionPack, String version)
   在 SquareMinecraftLauncher.Core.ForgeCore.ForgeJson(String version, String ForgePath)
   在 SquareMinecraftLauncher.Minecraft.Tools.<ForgeInstallation>d__10.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 demoForms.Form1.<button1_Click>d__1.MoveNext() 位置 C:\Users\Administrator\Desktop\服务器\demoForms\Form1.cs:行号 30
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4180.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
demoForms
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Administrator/Desktop/%E6%9C%8D%E5%8A%A1%E5%99%A8/demoForms/bin/Debug/demoForms.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4150.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4001.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4180.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
SquareMinecraftLauncherCore
    程序集版本:3.4.0.0
    Win32 版本:3.4.0.0
    基本代码:file:///C:/Users/Administrator/Desktop/%E6%9C%8D%E5%8A%A1%E5%99%A8/demoForms/bin/Debug/SquareMinecraftLauncherCore.DLL
----------------------------------------
Newtonsoft.Json
    程序集版本:12.0.0.0
    Win32 版本:12.0.2.23222
    基本代码:file:///C:/Users/Administrator/Desktop/%E6%9C%8D%E5%8A%A1%E5%99%A8/demoForms/bin/Debug/Newtonsoft.Json.DLL
----------------------------------------
ICSharpCode.SharpZipLib
    程序集版本:0.86.5.0
    Win32 版本:0.86.5.0
    基本代码:file:///C:/Users/Administrator/Desktop/%E6%9C%8D%E5%8A%A1%E5%99%A8/demoForms/bin/Debug/ICSharpCode.SharpZipLib.DLL
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.8.4180.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.8.4121.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。`
希望能得到您的解决方案。

**Comment by baibao132** [comment]
请确认该版本名称与versions文件夹中的1.14.4版本文件夹名相同
