### ISSUE TITLE
3.9.1版本assets下载问题

### ISSUE THREAD

**Issue by XiaoYejunAWA** [baibao132/SquareMinecraftLauncherCore#23]
执行await assetDownload.BuildAssetDownload(5, "1.8.1");语句后报错

System.NullReferenceException
  HResult=0x80004003
  Message=未将对象引用设置到对象的实例。
  Source=SquareMinecraftLauncherCore
  StackTrace:
   在 SquareMinecraftLauncher.Minecraft.AssetDownload.<Process_OutputDataReceived>d__11.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

**Comment by YUXUAN888** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baibao132/SquareMinecraftLauncherCore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月19日(星期天) 中午12:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[baibao132/SquareMinecraftLauncherCore] 3.9.1版本assets下载问题 (Issue #23)

我也不知道为啥给baibao的右键会送到我这来
你看看版本文件夹json有吗，我记得我以前没有就是这个报错


 
执行await assetDownload.BuildAssetDownload(5, "1.8.1");语句后报错
 
System.NullReferenceException
 HResult=0x80004003
 Message=未将对象引用设置到对象的实例。
 Source=SquareMinecraftLauncherCore
 StackTrace:
 在 SquareMinecraftLauncher.Minecraft.AssetDownload.<Process_OutputDataReceived&gt;d__11.MoveNext()
 在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
 在 System.Threading.ThreadPoolWorkQueue.Dispatch()
 
此异常最初是在此调用堆栈中引发的:
 [外部代码]

**Comment by baibao132** [comment]
下一个版本3.9.2会修复asset下载问题提高大量速度 会于元旦当天发布

**Comment by baibao132** [comment]
版本已经发布 具体内容可在https://github.com/baibao132/SquareMinecraftLauncherCore/issues/24 查看
