### ISSUE TITLE
4.0.2 版本微软登录问题

### ISSUE THREAD

**Issue by WinExp** [baibao132/SquareMinecraftLauncherCore#27]
这是通过refresh_token进行mc登录的代码（写的不好，勿喷）：
`MicrosoftLogin microsoftLogin = new MicrosoftLogin();`
`Xbox XboxLogin = new Xbox();`
`var Microsoft_Refresh_Token = con.GetStringValue("microsoft_refresh_token");`
`var Microsoft_Token = microsoftLogin.RefreshingTokens(Microsoft_Refresh_Token);`
`var Xbox_Token = XboxLogin.GetToken(Microsoft_Token);`
`var Xbox_Code = XboxLogin.XSTSLogin(Xbox_Token);`
`string Minecraft_Token = new MinecraftLogin().GetToken(Xbox_Code);`
`MinecraftLogin minecraftLogin = new();`
`var Minecraft = minecraftLogin.GetMincraftuuid(Minecraft_Token);`
`string uuid = Minecraft.uuid;`
`string name = Minecraft.name;`
`string[] list = { uuid, name };`
`return list;`
这是通过refresh_token进行mc登录的代码
当执行到这行代码时报错：
`var Xbox_Token = XboxLogin.GetToken(Microsoft_Token)`
错误：
System.NullReferenceException:“未将对象引用设置到对象的实例。”
查看`microsoftLogin.RefreshingTokens(Microsoft_Refresh_Token);`的返回值发现返回值为空
请问是我代码的问题吗

**Comment by baibao132** [comment]
明天将会发布新的版本，说不定能够解决该问题，如使用新版本还存在该问题，请核实确认所有参数都正确。

**Comment by baibao132** [comment]
新版本已发布 可以试试看哦

**Comment by WinExp** [comment]
emmm
但是这个api没有自定义minecraft文件夹的功能。
（改源代码改到手软的我）

**Comment by WinExp** [comment]
别的api要不然就是文档不完善，要不然就是有bug

**Comment by WinExp** [comment]
想做一个完美启动器（qwq）

**Comment by WinExp** [comment]
对了还有，记得更新下文档，微软登录那边参数填错了...

**Comment by baibao132** [comment]
自定义文件夹功能是有的，可以查看wiki

**Comment by baibao132** [comment]
public void SetMinecraftFilesPath(string Path)

解释：修改.Minecraft路径 参数:新.minecraft路径(无需指定到.minecraft文件夹里，只能指定到.minecraft文件夹外)
Tools类

**Comment by WinExp** [comment]
我指的是.minecraft也可以自定义qwq
（强迫症）

**Comment by WinExp** [comment]
我看源码是取程序运行目录+".minecraft"

**Comment by WinExp** [comment]
（有个地方）

**Comment by baibao132** [comment]
那修改的相关代码可以fork下吗？因为开源从联机增加之后 后面就不再开源了 因为开源不方便 所以相关bug修复和新增功能只在nuget里

**Comment by WinExp** [comment]
您是指我修改之后的吗？

**Comment by baibao132** [comment]
对

**Comment by WinExp** [comment]
等我上传到github嘿嘿

**Comment by WinExp** [comment]
网不太好

**Comment by WinExp** [comment]
vpn用的是1mbps的（悲

**Comment by baibao132** [comment]
我vpn都是买的 github就是这里不方便

**Comment by WinExp** [comment]
请问明天可以吗（今天传上去了会让你fork）

**Comment by baibao132** [comment]
可以的 还有在近期1个月内库会推出联机大厅功能 能够跨启动器联机和跨启动器多人房间 类似于网易联机大厅

**Comment by WinExp** [comment]
好的

**Comment by WinExp** [comment]
（我还看到了可以同步mod）

**Comment by baibao132** [comment]
是的

**Comment by WinExp** [comment]
想问一下这是什么原理（不方便透漏的话可以不说）

**Comment by WinExp** [comment]
github下载出问题了

**Comment by WinExp** [comment]
会404

**Comment by WinExp** [comment]
（刚刚发现的）

**Comment by baibao132** [comment]
其实就是利用端口转发实现的 还有一部分就不能明说了

404正常 我上传还经常404

**Comment by WinExp** [comment]
还有些地方有bug，明天给您

**Comment by YUXUAN888** [comment]
431127283
加群讨论哦

**Comment by WinExp** [comment]
好的

**Comment by WinExp** [comment]
> 431127283 加群讨论哦

好的
