### ISSUE TITLE
无法自动下载安装fabric

### ISSUE THREAD

**Issue by ClemensMine** [baibao132/SquareMinecraftLauncherCore#4]
使用的版本: 1.17.1
需要安装fabric的版本: 0.11.6
使用的代码
`            SquareMinecraftLauncher.Core.fabricmc.fabricmc fabricmc = new SquareMinecraftLauncher.Core.fabricmc.fabricmc();
            bool b = await fabricmc.FabricmcVersionInstall("1.17.1","0.11.6");`
启动后debug提示false

本软件目录下已存在.minecraft文件夹且1.17.1原版完整版成功安装

**Comment by baibao132** [comment]
目前问题已解决，可以通过nuget下载新版本的库
