### ISSUE TITLE
启动时一直显示 缺少Libraries文件

### ISSUE THREAD

**Issue by BiDuang** [baibao132/SquareMinecraftLauncherCore#9]
启动时一直显示器 缺少Libraries文件，可它们都在
尝试了路径补全和指定目录，也不行
1.17.1 1.16.5 1.12.2都不能启动 1.7.10却可以

**Comment by MRHedan** [comment]
我也是

**Comment by baibao132** [comment]
感谢您的反馈，近期会核实问题给出解决方案

**Comment by BiDuang** [comment]
好的

**Comment by baibao132** [comment]
经检测，确实存在启动问题，解决方案：java改用jdk后将可解决问题，对于libraries一直提示缺少问题可能是真的缺少，可以通过断点找到该数组去排查问题，也不排除因为网络问题无法下载文件。后续获取java版本我们会在下个版本更新，能够获取jdk和jre两种版本类型。

**Comment by BiDuang** [comment]
libs应该不会缺少，使用PCL能够正常启动
而且还使用了下载补全文件的函数，确认了没有缺少文件，但仍然提示缺少libs文件然后引发崩溃。另外，我使用的java都是jdk11和jdk16，一样不能启动1.17.1和1.16.5，除1.7.10可以正常启动其余都不能正常启动

**Comment by BiDuang** [comment]
也已经经过短点查找过了，就是最后启动游戏进程那一句，显示缺少libs

**Comment by baibao132** [comment]
请提供一下相关版本启动失败的日志。
也可以尝试删除游戏版本和libraries目录通过我们提供的函数下载补全好游戏再次进行启动，说不定问题会直接解决

**Comment by baibao132** [comment]
要是安装了forge等相关扩展，请直接删除版本 通过本库进行相关操作。

**Comment by YUXUAN888** [comment]
我也是这种问题，原版1.12.2不能启动，提示缺少Libraries，但是其他任何一个启动器都可以

**Comment by YUXUAN888** [comment]
使用jdk14也不行

**Comment by baibao132** [comment]
那在下一个版本中我会将启动代码里的libraries函数删除 就可以解决这些问题了
